apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hellomiragespt
spec:
  template:
    spec:
      runtimeClassName: urunc
      containers:
        - image: harbor.nbfc.io/nubificus/knative-example-functions/mirage-httpreply-spt:latest
          imagePullPolicy: Always
          env:
            - name: RUNTIMECLASS
              value: "generic"
